feat(table): add table component
indec-it/react-native-table pull request #1
Opened 2018-01-12 14:34 UTC by maximilianoforlenza

feat(table): add table component

2018-01-12 15:53 UTC, navarroaxel requested changes

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +        <View>
Creo que este `View` se puede sacar.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +import RenderComponent from '../mapComponents/index';
achica este `import` poniendo: `from '../mapComponents'`

2018-01-12 15:53 UTC, navarroaxel commented on src/mapComponents/index.js
> +const RenderComponent = ({child, item}) => {
la carpeta no coincide con el component name. Este component sólo se usa en el `Table` component podrías ponerlo como sub-carpeta. Más si es un component privado de este package.

2018-01-12 15:53 UTC, navarroaxel commented on src/index.js
> +export default Table;
Además de la `Table` deberías exportar el `componentTypeEnum`

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                        key={`dwelling-${item._id}`}
Si es una `Table` genérica esta `key` no debería ser `dwelling`.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/styles.js
> +    container: {
Busco pero me parece que nadie usa este `container` style.

2018-01-12 15:53 UTC, navarroaxel commented on src/mapComponents/styles.js
> +        flexDirection: 'column'
Busco pero me parece que nadie usa este `container` style.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                            {!isEmpty(buttons) && buttons.map(button => (!button.childrenButtons ? (
No me gusta tantos condicionales acá, xq no lo pasamos a una `function` o `arrow function` y reemplazamos esto por `{buttons && this.renderButtons(...)}`

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                                    flexSize={button.flexSize}
esta prop es `size`.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                                    key={`head-${prop.field}${item._id}`}
esto no es una cabera, no entiendo xq este prefijo. Las `key` prop son locales al map, no globales a la app. Saca el prefijo y el `item._id`.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                                    key={`button-${button.icon.name}${item._id}`}
sacar el prefijo del `key` y sacar el `item._id`

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                <Col key={button.fieldName} flexSize={button.flexSize}>
es `size` la prop.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                                <Row flexSize={button.childrenFlexSize}>
es `size` la prop.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +    items: PropTypes.arrayOf(PropTypes.shape({})),
Para una mejor doc sería bueno poner todo el `shape` que debe tener el objeto. en todos los `propTypes`

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/styles.js
> +    containerCheckbox: {
De todo este archivo de estilos sólo se usa el `containerCheckbox`, renombrar a `checkbox`.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +    <View style={styles.container}>
Si esta `View` usa estilos de `col` quizá debería ser el component `Col`.

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                    <TextStrong style={styles.textItemHead}>{prop.fieldName}</TextStrong>
renombra el estilo a `itemHeader`

2018-01-12 15:53 UTC, navarroaxel commented on src/Table/index.js
> +                        style={[styles.rowDefault]}
Acá las `[]` del style están de mas. Renombrar estilo a `row` no hay filas que no tengan el estilo `"default"`.

2018-01-12 16:00 UTC, maximilianoforlenza commented on src/Table/styles.js
> +    container: {
en la View que contiene la tabla

2018-01-12 16:07 UTC, maximilianoforlenza commented
listo @navarroaxel

2018-01-12 16:10 UTC, navarroaxel requested changes

2018-01-12 16:10 UTC, navarroaxel commented on src/Table/mapComponents/index.js
> +            return (<Icon
Este `Icon` retorna una `key` pero el `CheckBox` de abajo no. Esto debería ser consistente.

2018-01-12 18:19 UTC, maximilianoforlenza commented on src/Table/mapComponents/index.js
> +            return (<Icon
No hace falta que lo tenga ya que la key la tiene el RenderComponent cuando la llama la Table

2018-01-14 16:00 UTC, navarroaxel requested changes

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +    attributes: PropTypes.arrayOf(PropTypes.shape({
si estos `attributes` son las columnas creo que sería más claro renombrarlo a `columns`.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +        fieldName: PropTypes.string.isRequired,
`fieldName` debería ser renombrado a `text` o `label` para que quede claro que es el nombre de la columna.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +    items: PropTypes.arrayOf(PropTypes.shape({})),
si este es el `data source` de la `Table` debería renombrarse a `rows` o a `data`.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/tableComponents/index.js
> +const TableComponent = ({child, item}) => {
No usamos `Component` como parte del nombre de componentes. y el nombre de la carpeta contenedora debería ser en `PascalCase`. Por el comportamiento que tiene este component debería llamarse `TableButton`.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +import RenderComponent from './tableComponents';
acá estás renombrando el componente. Esto hace el código más dificil de seguir.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/tableComponents/index.js
> +        component: PropTypes.shape({
Te falto poner el `callback` en las PropTypes, creo que este objeto se debería aplanar.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/tableComponents/index.js
> +            name: PropTypes.string.isRequired,
esto no debería ser `name`, no se entiende si es un `field` o un `label`. Debería llamarse `icon`. O dentro de un objeto `icon` que este el `name` y el `color`: `icon: {name, color}`

2018-01-14 16:00 UTC, navarroaxel commented on src/constants/index.js
> +export default {
este archivo debería ser renombrado con el nombre del `enum`.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +    buttons: PropTypes.arrayOf(PropTypes.shape({}))
flexSize no está en las Props. renombralo a `size`. el childrenFlexSize renombralo a `childrenSize`

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +                    {!isEmpty(buttons) && buttons.map(button => (!button.childrenButtons ? (
ente `render` de buttons sacalo a una `function` así queda más claro. e invertí el condional del `?:` que quedaría más claro.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +                            {button.childrenButtons.map(child => (
De verdad un button puede tener más de un Button?

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +                            key={`head-${prop.field}${item._id}`}
la `key` debería ser simplemente: `key={prop.field}`.

2018-01-14 16:00 UTC, navarroaxel commented on src/Table/index.js
> +                        <Col
esto es un `map` y no tienen `key`.

2018-01-25 18:20 UTC, navarroaxel requested changes

2018-01-25 18:20 UTC, navarroaxel commented on src/Table/TableIcon.js
> +    column: PropTypes.shape(columnPropType).isRequired,
`column: columnPropType`

2018-01-25 18:20 UTC, navarroaxel commented on src/Table/TableIcon.js
> +    datum: PropTypes.shape({}).isRequired
poneselos a todos los `datum`.

2018-01-26 01:26 UTC, maximilianoforlenza commented
listo

2018-01-26 11:33 UTC, navarroaxel approved these changes

2018-01-26 11:34 UTC, merged