feat(table): add styles and dividers
indec-it/react-native-table pull request #2
Opened 2018-01-28 06:52 UTC by maximilianoforlenza

feat(table): add styles and dividers

2018-01-28 19:37 UTC, navarroaxel requested changes

2018-01-28 19:37 UTC, navarroaxel commented on src/Table/styles.js
> +    headContainer: {
cuando lo usas lo llamas `headerContainer`.

2018-01-28 19:37 UTC, navarroaxel commented on src/Table/TableRow.js
> +        <Divider style={[styles.itemsDivider, {backgroundColor: '#dcdcdc'}]}/>
genera antes los 2 styles para los divisores así ahorras CPU. Podes hacerlo usando `https://facebook.github.io/react-native/docs/stylesheet.html#flatten` o sino usando el operador `...`.

2018-01-28 20:14 UTC, maximilianoforlenza commented
listo

2018-01-29 12:29 UTC, navarroaxel approved these changes

2018-01-29 12:48 UTC, merged